[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "redforge"
version = "0.1.0"
description = "RedForge - Offensive Security Workspace"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Arpit Toppo" }
]
dependencies = [
    "PySide6",
    "SQLAlchemy",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]